# Authelia Configuration (simple dev setup)
server:
  # New schema: use address only (port/host/path deprecated)
  address: 'tcp://0.0.0.0:9091'
  buffers:
    read: 4096
    write: 4096

log:
  level: debug

# jwt_secret moved to identity_validation.reset_password.jwt_secret per deprecation notice

identity_validation:
  reset_password:
    jwt_secret: 'dev_jwt_secret_change_me'

# Use file-based users for dev/testing
authentication_backend:
  file:
    path: /config/custom/users.yml
    watch: false
    password:
      algorithm: argon2id
      iterations: 3
      key_length: 32
      salt_length: 16
      memory: 65536
      parallelism: 4

# Enforce stronger user password requirements (dev defaults; adjust for prod)
password_policy:
  standard:
    enabled: true
    min_length: 12
    max_length: 128
    require_number: true
    require_lowercase: true
    require_uppercase: true
    require_special: true

session:
  name: authelia_session
  secret: 'dev_session_secret_change_me'
  expiration: 3600
  inactivity: 300
  # New schema: per-cookie configuration; do not also set session.domain
  cookies:
    - name: authelia_session
      domain: fkstrading.xyz
      authelia_url: https://auth.fkstrading.xyz
      default_redirection_url: https://fkstrading.xyz/
      same_site: lax
    - name: authelia_session
      domain: fkstrading.test
      authelia_url: https://auth.fkstrading.test
      default_redirection_url: https://fkstrading.test/
      same_site: lax

# Local memory storage (no Redis) for simplicity
storage:
  # Required by recent Authelia versions
  encryption_key: 'dev_storage_encryption_key_change_me_please_32chars+'
  local:
    path: /config/authelia.db

# Simple access control: everything requires authentication unless skipped
access_control:
  default_policy: two_factor
  rules:
    - domain:
        - '*.fkstrading.xyz'
        - 'fkstrading.xyz'
        - '*.fkstrading.test'
        - 'fkstrading.test'
      policy: one_factor
      resources:
        - '^/api.*'
        - '^/data.*'
        - '^/engine.*'
        - '^/transformer.*'
        - '^/ws.*'

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
