apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: fks-development
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      receiver: 'default'
    receivers:
      - name: 'default'
