apiVersion: v1
kind: ConfigMap
metadata:
  name: fks-pine-config
  namespace: fks-development
data:
  APP_LOG_LEVEL: info
  CONFIG_DIR: /app/config
  CONFIG_FILE: /app/config/fks/pine.yaml
  PYTHONPATH: /app/src
  PYTHONUNBUFFERED: '1'
  SERVICE_RUNTIME: python
  SERVICE_TYPE: pine
  TZ: America/Toronto
  KEEP_CONTAINER_ALIVE: 'true'
  SYMBOL: BTCUSD
