apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: fks-development
data:
  redis.conf: |
    # Redis configuration file
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300

    # Logging
    loglevel notice
    logfile ""

    # Persistence
    dbfilename dump.rdb
    dir /data

    # Memory
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Replication
    replica-serve-stale-data yes
    replica-read-only yes
