apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fks_web-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
