# XGBoost and other models configuration

# Random Forest classifier model parameters
random_forest:
  n_estimators: 100
  max_depth: 10
  random_state: 42
  class_weight: "balanced"
  min_samples_split: 2
  min_samples_leaf: 1

# Polynomial features parameters
polynomial:
  degree: 3
  include_bias: true
  interaction_only: false

# XGBoost model parameters
xgboost:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 5
  subsample: 0.8
  colsample_bytree: 0.8
  objective: "reg:squarederror"