apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: api-service
