apiVersion: v1
kind: Service
metadata:
  name: datadog
  namespace: fks_development
  labels:
    app: datadog
spec:
  type: ClusterIP
  ports:
  - name: dd-agent
    protocol: TCP
    port: 8126
    targetPort: 8126
  selector:
    app: datadog
