apiVersion: v1
kind: Service
metadata:
  name: fks_worker-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: fks_worker
