apiVersion: v1
kind: Service
metadata:
  name: fks-data-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: fks-data
