apiVersion: v1
kind: Service
metadata:
  name: fks-watcher-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8087
    targetPort: 8087
  selector:
    app: fks-watcher
