apiVersion: v1
kind: Service
metadata:
  name: fks-training-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8086
    targetPort: 8086
  selector:
    app: fks-training
