apiVersion: v1
kind: Service
metadata:
  name: fks_pine-service
  namespace: fks_development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8085
    targetPort: 8085
  selector:
    app: fks_pine
