apiVersion: v1
kind: Service
metadata:
  name: fks_training-service
  namespace: fks_development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8086
    targetPort: 8086
  selector:
    app: fks_training
