apiVersion: v1
kind: Service
metadata:
  name: fks-web-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  selector:
    app: fks-web
