apiVersion: v1
kind: Service
metadata:
  name: fks_watcher-service
  namespace: fks_development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8087
    targetPort: 8087
  selector:
    app: fks_watcher
