apiVersion: v1
kind: Service
metadata:
  name: fks_app-service
  namespace: fks_development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app: fks_app
