apiVersion: v1
kind: Service
metadata:
  name: fks-pine-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8085
    targetPort: 8085
  selector:
    app: fks-pine
