apiVersion: v1
kind: Service
metadata:
  name: fks_api-service
  namespace: fks_development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: fks_api
