apiVersion: v1
kind: Service
metadata:
  name: fks-app-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app: fks-app
