apiVersion: v1
kind: Service
metadata:
  name: fks_data-service
  namespace: fks_development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: fks_data
