apiVersion: v1
kind: Service
metadata:
  name: fks-api-service
  namespace: fks-development
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: fks-api
