apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: fks_development
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
