apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fks-development
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - name: database
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
