apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: fks-development
  labels:
    app: postgres-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 9187
    targetPort: 9187
  selector:
    app: postgres-exporter
