apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: fks_development
  labels:
    app: prometheus
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
