apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fks-development
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - name: database
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis
