apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: fks_development
  labels:
    app: redis-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 9121
    targetPort: 9121
  selector:
    app: redis-exporter
