apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: # Let kubeadm generate a token automatically
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
localAPIEndpoint:
  advertiseAddress: 100.115.54.104
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
imageRepository: registry.k8s.io
kubernetesVersion: 1.33.0
networking:
  dnsDomain: fkstrading.xyz
  podSubnet: 10.11.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServer:
  timeoutForControlPlane: 4m0s
  # You can add custom API server settings here
controllerManager: {}
scheduler: {}
etcd:
  local:
    dataDir: /var/lib/etcd
dns:
  # Uncomment to customize CoreDNS configuration
  # imageRepository: registry.k8s.io
  # imageTag: 1.9.4