apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fks-pine-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: fks-pine-service-account
  namespace: fks-development
roleRef:
  kind: ClusterRole
  name: fks-pine-clusterrole
  apiGroup: rbac.authorization.k8s.io
