apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fks-training-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: fks-training-service-account
  namespace: fks-development
roleRef:
  kind: ClusterRole
  name: fks-training-clusterrole
  apiGroup: rbac.authorization.k8s.io
