# Kubernetes ClusterRoles Configuration
k8s:
  clusterroles:
    # Added from datadog-clusterrole.yaml
    - name: datadog-clusterrole
      rules:
        - apiGroups: [""]
          resources:
            - nodes
            - pods
            - services
            - endpoints
            - events
            - namespaces
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["apps"]
          resources:
            - deployments
            - replicasets
            - statefulsets
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["batch"]
          resources:
            - jobs
            - cronjobs
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["autoscaling"]
          resources:
            - horizontalpodautoscalers
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["metrics.k8s.io"]
          resources:
            - pods
            - nodes
          verbs:
            - get
            - list
            - watch
    
    # Added from fks-app-clusterrole.yaml
    - name: fks-api-clusterrole
      rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
    
    - name: fks-app-clusterrole
      rules:
        - apiGroups: [""]
          resources:
            - nodes
            - pods
            - services
            - endpoints
            - events
            - namespaces
            - configmaps
            - secrets
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["apps"]
          resources:
            - deployments
            - replicasets
            - statefulsets
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["batch"]
          resources:
            - jobs
            - cronjobs
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["autoscaling"]
          resources:
            - horizontalpodautoscalers
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["metrics.k8s.io"]
          resources:
            - pods
            - nodes
          verbs:
            - get
            - list
            - watch
    
    - name: fks-data-clusterrole
      rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
    
    - name: fks-pine-clusterrole
      rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
    
    - name: fks-training-clusterrole
      rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
    
    - name: fks-watcher-clusterrole
      rules:
        - apiGroups: [""]
          resources: ["pods", "services", "endpoints", "nodes"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["apps"]
          resources: ["deployments", "statefulsets"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["batch"]
          resources: ["jobs", "cronjobs"]
          verbs: ["get", "list", "watch"]
    
    - name: fks-web-clusterrole
      rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
    
    - name: fks_worker-clusterrole
      rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["batch"]
          resources: ["jobs"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    
    # Added from nginx-ingress-clusterrole.yaml
    - name: nginx-ingress-clusterrole
      rules:
        - apiGroups:
            - ""
          resources:
            - configmaps
            - endpoints
            - nodes
            - pods
            - secrets
            - services
          verbs:
            - list
            - watch
        - apiGroups:
            - "networking.k8s.io"
          resources:
            - ingressclasses
            - ingresses
            - ingresses/status
          verbs:
            - get
            - list
            - watch
            - update
        - apiGroups:
            - "coordination.k8s.io"
          resources:
            - leases
          verbs:
            - create
            - get
            - update