# Kubernetes Role Bindings Configuration
k8s:
  role-bindings:
    - name: pod-reader-binding
      namespace: default
      role: pod-reader
      subjects:
        - kind: ServiceAccount
          name: app-service-account
          namespace: default
    - name: datadog-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: datadog-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: datadog-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_api-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_api-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_api-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_app-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_app-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_app-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_data-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_data-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_data-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_pine-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_pine-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_pine-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_training-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_training-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_training-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_watcher-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_watcher-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_watcher-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_web-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_web-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_web-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: fks_worker-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: fks_worker-service-account
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: fks_worker-clusterrole
        apiGroup: rbac.authorization.k8s.io
    - name: nginx-ingress-clusterrolebinding
      subjects:
        - kind: ServiceAccount
          name: nginx-ingress
          namespace: fks_development
      roleRef:
        kind: ClusterRole
        name: nginx-ingress-clusterrole
        apiGroup: rbac.authorization.k8s.io