apiVersion: v1
kind: PersistentVolume
metadata:
  name: fks-app-src-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: fks/src
