# Chart styles configuration

# Chart configuration
charts:
  # Default chart colors
  colors:
    gold:
      line: "#FFD700"
      fill: "rgba(255, 215, 0, 0.1)"
      prediction: "#FFA500"
    bitcoin:
      line: "#F7931A"
      fill: "rgba(247, 147, 26, 0.1)"
      prediction: "#B22222"
    silver:
      line: "#C0C0C0"
      fill: "rgba(192, 192, 192, 0.1)"
      prediction: "#708090"
    ethereum:
      line: "#627EEA"
      fill: "rgba(98, 126, 234, 0.1)"
      prediction: "#3C3C3D"
    up: "rgba(0, 128, 0, 0.7)"
    down: "rgba(255, 0, 0, 0.7)"
    neutral: "rgba(100, 100, 100, 0.5)"
    grid: "#EEEEEE"
    background: "rgba(0, 0, 0, 0)"

  # Chart layout defaults for consistency
  default_layout:
    paper_bgcolor: "rgba(0, 0, 0, 0)"
    plot_bgcolor: "rgba(0, 0, 0, 0)"
    font:
      color: "#333333"
      family: "Arial, sans-serif"
      size: 12
    xaxis:
      gridcolor: "#EEEEEE"
      zeroline: false
      showspikes: true
      spikemode: "across"
      spikethickness: 1
    yaxis:
      gridcolor: "#EEEEEE"
      zeroline: false
      showspikes: true
      spikemode: "across"
      spikethickness: 1
    legend:
      orientation: "h"
      yanchor: "bottom"
      y: 1.02
      xanchor: "right"
      x: 1
    hovermode: "x unified"
    margin:
      l: 40
      r: 40
      t: 40
      b: 40
    showlegend: true
    autosize: true
    dragmode: "zoom"

  # Timeframe options for charts
  timeframe_options:
    - label: "1 Day"
      value: "1d"
    - label: "1 Week"
      value: "1w"
    - label: "1 Month"
      value: "1m"
    - label: "3 Months"
      value: "3m"
    - label: "6 Months"
      value: "6m"
    - label: "1 Year"
      value: "1y"
    - label: "YTD"
      value: "ytd"
    - label: "All"
      value: "all"