apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadog-data
  namespace: fks_development
  labels:
    app: datadog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
