apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fks_worker-data-pvc
  namespace: fks-development
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
