apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fks_model-storage-pvc
  namespace: fks_development
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
