apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fks_app-data-pvc
  namespace: fks_development
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
