apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-logs-pvc
  namespace: fks-development
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
