apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-logs-pvc
  namespace: fks-development
  labels:
    app: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
