apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: myrepo/api-service:${IMAGE_TAG:-latest}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
        - name: CONFIG_ENV
          value: development
