apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: fks_development
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: timezone-config
              key: TZ
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-data-pvc
          mountPath: /var/lib/grafana
        - name: grafana-logs
          mountPath: /var/log/grafana
        - name: grafana-config
          mountPath: /etc/grafana/provisioning
      volumes:
      - name: grafana-data-pvc
        persistentVolumeClaim:
          claimName: grafana-data-pvc
      - name: grafana-logs
        emptyDir: {}
      - name: grafana-config
        emptyDir: {}
