apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-deployment
  namespace: fks_development
  labels:
    app: nginx-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ingress-deployment
  template:
    metadata:
      labels:
        app: nginx-ingress-deployment
    spec:
      containers:
      - name: nginx-ingress
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
      serviceAccountName: nginx-ingress-sa
