apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: fks_development
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: fks_app-config
              key: TZ
        ports:
        - containerPort: 9121
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
          requests:
            memory: 64Mi
            cpu: 250m
      imagePullSecrets:
      - name: regcred
